# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }
#
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.

title: Your awesome title
email: gmarress@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  A personal site to exhibit the interesting and wonderful ideas and projects
  that have been accomplished using code. This website is hosted on GitHub.
  Gideonamani A. Marress is the web admin.

baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://example.com" # the base hostname & protocol for your site

twitter_username: Gideonamani
github_username:  Gideonamani

favicon: "favicon.ico"

# Build settings
markdown: kramdown
theme: minima

port: 4004


collections:
  blogstuff:
    output: TRUE
    lang: en
    permalink: /:path/

  blogstuff-sw:
    output: TRUE
    permalink: /:path/sw/
    lang: sw
